services:
  app:
    container_name: staging_app
    image: ${DOCKERHUB_USERNAME}/bbegok:staging
    platform: linux/arm64
    ports:
      - "8090:8080"
    environment:
      - ENV=${ENV}
    depends_on:
      - db
      - redis

  portainer:
    image: portainer/portainer-ce
    volumes:
      - portainer-data-staging:/data

  db:
    container_name: staging_db
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: staging-bbaegok
      TZ: UTC                         #Linux 컨테이너 타임존 설정
    command: --default-time-zone='+00:00' #MySQL 컨테이너
    volumes:
      - mysql-data-staging:/var/lib/mysql

  nginx:
    container_name: staging_nginx
    image: nginx:latest
    ports:
      - "444:443"
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/var/www/html:rw
    depends_on:
      - app
      - portainer

  redis:
    container_name: staging_redis
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis-data-staging:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mysql-data-staging:
  redis-data-staging:
  portainer-data-staging:

x-dockerhub-auth:
  username: ${DOCKERHUB_USERNAME}
  password: ${DOCKERHUB_TOKEN}
