services:
  app:
    image: ${DOCKERHUB_USERNAME}/bbegok:latest
    platform: linux/arm64/v8
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bbegok?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bbegok
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./configuration/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  mysql-data:
x-dockerhub-auth: &dockerhub-auth
  username: ${DOCKERHUB_USERNAME}
  password: ${DOCKERHUB_TOKEN}
