services:
  app:
    image: ${DOCKERHUB_USERNAME}/bbegok:latest
    platform: linux/arm64
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bbegok?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

  portainer:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bbegok
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - BACKEND_SERVICE=app:8080
    depends_on:
      - app
      
volumes:
  mysql-data:
  portainer_data:
  
x-dockerhub-auth: &dockerhub-auth
  username: ${DOCKERHUB_USERNAME}
  password: ${DOCKERHUB_TOKEN}

