services:
  app:
    image: ${DOCKERHUB_USERNAME}/bbegok:latest
    platform: linux/arm64
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
	    SPRING_DATASOURCE_URL: ${MYSQL_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}

  portainer:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bbegok
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
	    - ${SSL_CERT_PATH}:/etc/nginx/ssl
    depends_on:
      - app
      - portainer


volumes:
  mysql-data:
  portainer_data:
  
x-dockerhub-auth: &dockerhub-auth
  username: ${DOCKERHUB_USERNAME}
  password: ${DOCKERHUB_TOKEN}
