name: Deploy to RaspberryPi Server
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17 for ARM64 #ARM64 버전으로 JDK셋팅
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" >> $GITHUB_ENV
    
    - name: Build with Gradle  #프로젝트빌드
      run: |
        chmod +x ./gradlew
        $JAVA_HOME/bin/java -version
        ./gradlew build

    - name: Find Docker
      run: |
        which docker || echo "Docker not found in PATH"
    
    - name: Check Docker symlinks
      run: |
        ls -l /usr/bin/docker

    - name: Check environment
      run: |
        echo $PATH
        env

    - name: Build Docker image  #도커이미지 빌드
      run: |
        sudo /usr/bin/docker build -t bbegok:latest .

    - name: Update docker-compose.yml  #새이미지로 업데이트
      run: |
        sed -i 's|image: .*|image: bbegok:latest|' docker-compose.yml

    - name: Deploy with Docker Compose #배포
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: |
        echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" > .env
        echo "MYSQL_USER=$MYSQL_USER" >> .env
        echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
        docker-compose down
        docker-compose up -d

    - name: Reload Nginx ##Nginx 재로드
      run: |
        sudo cp nginx.conf /etc/nginx/sites-available/bbegok
        sudo ln -sf /etc/nginx/sites-available/bbegok /etc/nginx/sites-enabled/
        sudo nginx -t && sudo systemctl reload nginx
