name: Deploy to RaspberryPi Server
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17 for ARM64 #ARM64 버전으로 JDK셋팅
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk
        echo "JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::")" >> $GITHUB_ENV
    
    - name: Build with Gradle  #프로젝트빌드
      run: |
        chmod +x ./gradlew
        $JAVA_HOME/bin/java -version
        ./gradlew build
        
    - name: Ensure Docker daemon is running
      run: |
        if ! pgrep -x "dockerd" > /dev/null
        then
          sudo dockerd &
          sleep 10
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker buildx build --platform linux/arm64 -t bbegok:latest .

    - name: Update docker-compose.yml
      run: |
        sed -i 's|image: .*|image: bbegok:latest|' docker-compose.yml

    - name: Deploy with Docker Compose #배포
      env:
        MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      run: |
        echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" > .env
        echo "MYSQL_USER=$MYSQL_USER" >> .env
        echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
        docker-compose down
        docker-compose up -d

    - name: Reload Nginx ##Nginx 재로드
      run: |
        cp nginx.conf /etc/nginx/sites-available/bbegok
        ln -sf /etc/nginx/sites-available/bbegok /etc/nginx/sites-enabled/
        nginx -t && sudo systemctl reload nginx
