name: Deploy to RaspberryPi Server
on:
  push:
    branches: [ main ]  #main브랜치 변화를 감지한다
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Build with Gradle  #프로젝트를 빌드하여 jar파일을 생성한다
      run: |
        cd back
        ./gradlew build
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image  #도커이미지를 생성하여 GRCR에 push한다
      uses: docker/build-push-action@v2
      with:
        context: ./back
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/bbegok:${{ github.sha }}

    - name: Copy docker-compose and nginx config to Raspberry Pi  #도커컴포즈와 NginX설정을 라즈베리파이에 복사한다
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USERNAME }}
        password: ${{ secrets.PI_PASSWORD }}
        source: "back/docker-compose.yml,back/nginx.conf"
        target: "/home/${{ secrets.PI_USERNAME }}/bbegok"
    
    - name: Deploy to Raspberry Pi  #라즈베리파이에서 Docker image를 받아 배포작업을 한다
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PI_HOST }}
        username: ${{ secrets.PI_USERNAME }}
        password: ${{ secrets.PI_PASSWORD }}
        script: |
          cd /home/${{ secrets.PI_USERNAME }}/bbegok
          echo "BBEGOK_IMAGE=ghcr.io/${{ github.repository_owner }}/bbegok:latest" > .env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
          docker-compose pull
          docker-compose up -d
